language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script:
  - ./gradlew test

jdk:
  - oraclejdk8

before_install:
  - chmod +x .buildscript/deploy_snapshot.sh

after_success:
  - .buildscript/deploy_snapshot.sh

cache:
  directories:
    - $HOME/.gradle

sudo: false
