language: android

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script:
  - ./gradlew test

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

cache:
  directories:
    - $HOME/.gradle

sudo: false

env:
  global:
    - secure TODO: BINTRAY_USER
    - secure TODO: BINTRAY_API_KEY
